[package]
name = "partner-management"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.3", features = ["postgres"] }
diesel_migrations = "2.1.0"
knuffel = "3.2.0"
miette = { version = "5.10.0", features = ["fancy"] }
poise = "0.5.7"

[dependencies.serenity]
version = "0.11.7"
default-features = false

[dependencies.tokio]
version = "1.33.0"
features = [
	"fs",
	"macros",
	"net",
	"rt-multi-thread",
	"sync"
]